# Copyright 2022 XMOS LIMITED.
# This Software is subject to the terms of the XMOS Public Licence: Version 1.
import argparse
import numpy as np
from pathlib import Path
from datetime import datetime

def parse_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", nargs='?', default='2 2 2 10 5', help="Build configuration in '<threads> <num_y_channels> <num_x_channels> <num_main_filter_phases> <num_shadow_filter_phases>' format. Default '2 2 2 10 5'")
    parser.add_argument("--out-dir", nargs='?', default='.', help="output directory to generate files in. Default .")
    args = parser.parse_args()
    return args

#Schedule num_tasks tasks, each having num_channels channels over num_threads threads
def gen_task_distribution(num_threads, num_tasks, num_channels):
    #Scheduling logic - T0C0, T1C0, T2C0, T0C1, T1C1, T2C2 and so on
    if num_channels:
        remaining_jobs = num_tasks * num_channels
    else:
        remaining_jobs = num_tasks
    pas = 0
    tdist = np.zeros((num_threads,1), dtype=np.int32)
    thread = 0

    task_index = 0
    ch_index = 0
    while(remaining_jobs):
        #bit 16:9 task_index, bit8:1 ch_index, bit0, is_active 
        tdist[thread, pas] = (1 | (((ch_index & 0xff) << 1) | ((task_index & 0xff) << 9)))
        task_index = task_index + 1
        if(task_index == num_tasks):
            task_index = 0
            if num_channels:
                ch_index = (ch_index + 1) % num_channels

        thread += 1
        remaining_jobs -= 1
        if(thread == num_threads and remaining_jobs): #add another pass
            thread = 0
            pas += 1
            append_sch = np.zeros((num_threads, 1), dtype=np.int32)
            tdist = np.hstack((tdist, append_sch))
    pas += 1
    return tdist

def print_task_distribution(tdist, num_tasks, num_channels, fp_tdist_h, fp_c, task_distribution_t_str):
    num_threads = tdist.shape[0]
    num_passes = tdist.shape[-1]
    threads_str = "AEC_THREAD_COUNT"
    if num_channels:
        passes_docsrt = f"""/** Number of iterations run on a given thread when distributing {num_tasks} tasks,
 * max(AEC_MAX_Y_CHANNELS, AEC_MAX_X_CHANNELS) channels across AEC_THREAD_COUNT number of threads*/\n"""
        passes_str = f"AEC_{num_tasks}_TASKS_AND_CHANNELS_PASSES"
        struct_typedef = "par_tasks_and_channels_t"
        task_distribution_t_str += f"""    /** task distribution definition for {num_tasks} tasks, max(AEC_MAX_Y_CHANNELS, AEC_MAX_X_CHANNELS) channels,
     * scheduled across AEC_THREAD_COUNT threads */\n"""
        task_distribution_t_str += f"    {struct_typedef} par_{num_tasks}_tasks_and_channels[{threads_str}][{passes_str}];\n"
    else:
        passes_docsrt = f"/** Number of iterations run on a given thread when distributing {num_tasks} tasks across AEC_THREAD_COUNT threads*/\n"
        passes_str = f"AEC_{num_tasks}_TASKS_PASSES"
        struct_typedef = "par_tasks_t"
        task_distribution_t_str += f"    /** task distribution definition for {num_tasks} tasks, scheduled across AEC_THREAD_COUNT threads */\n"
        task_distribution_t_str += f"    {struct_typedef} par_{num_tasks}_tasks[{threads_str}][{passes_str}];\n"

    fp_tdist_h.write(passes_docsrt)
    fp_tdist_h.write(f'#define {passes_str}   ({num_passes})' + '\n\n')
    fp_c.write("    {\n")
    for t in range(num_threads):
        thread_str = "        {" 
        for p in range(num_passes):
            task = (tdist[t][p] >> 9)
            ch = (tdist[t][p] >> 1) & 0xff
            active = tdist[t][p] & 1
            if num_channels:
                ph_str = "{" + f"{task}, {ch}, {active}" "}"
            else:
                ph_str = "{" + f"{task}, {active}" "}"
            thread_str = thread_str + ph_str + ','
        thread_str += "},"
        fp_c.write(thread_str+'\n')
    fp_c.write("    },\n")
    return task_distribution_t_str


def create_task_distribution():
    args = parse_arguments()
    print('config = ',args.config)
    out_dir = Path(args.out_dir).absolute()
    print('out-dir = ',out_dir)
    conf = args.config.split(' ')
    num_threads = int(conf[0])
    max_y_channels = conf[1]
    max_x_channels = conf[2]
    main_filter_phases = conf[3]
    shadow_filter_phases = conf[4]
    num_channels = max(int(max_y_channels), int(max_x_channels))
    print(f"AEC task distribution generation configured for {num_threads} threads, max {max_y_channels} y channels, max {max_x_channels} x channels, {main_filter_phases} main_filter_phases, {shadow_filter_phases} shadow_filter_phases")
    pragma_once = "#pragma once\n\n"
    file_header = f"""// Copyright {datetime.now().year} XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.

/* Do not edit, autogenerated */\n\n"""

    tdist_h_file_name = "aec_task_distribution.h"
    cfg_h_file_name = "aec_config.h"
    c_file_name = "aec_task_distribution.c"

    fp_cfg_h = open(out_dir / cfg_h_file_name, 'w')
    fp_cfg_h.write(file_header)
    fp_cfg_h.write(pragma_once)
    fp_cfg_h.write(f"#define AEC_THREAD_COUNT           ({num_threads})\n")
    fp_cfg_h.write(f"#define AEC_MAX_Y_CHANNELS         ({max_y_channels})\n")
    fp_cfg_h.write(f"#define AEC_MAX_X_CHANNELS         ({max_x_channels})\n")
    fp_cfg_h.write(f"#define AEC_MAIN_FILTER_PHASES     ({main_filter_phases})\n")
    fp_cfg_h.write(f"#define AEC_SHADOW_FILTER_PHASES   ({shadow_filter_phases})\n")
    fp_cfg_h.close()

    fp_tdist_h = open(out_dir / tdist_h_file_name, 'w')
    fp_tdist_h.write(file_header)
    fp_tdist_h.write(pragma_once)
    fp_tdist_h.write(f'#include "{cfg_h_file_name}"\n\n')

    fp_tdist_h_docstr = """/**
 * @page This header defines the data structures used when distributing tasks across hardware threads.
 *
 * The task distribution scheme distributes tasks across hardware threads for 2 scenarios.
 *      1. Distribute multiple unique tasks across multiple HW threads. For example, for a 3 tasks, 2 threads configuration,
 *         distribute [task0, task1, task2] across [Thread0, Thread1].
 *      2. Distribute multiple (task, channel) pairs across multiple HW threads. For example, for a 3 tasks, 2 channels, 2 threads
 *      configuration, distribute [(task0, ch0), (task0, ch1), (task1, ch0), (task1, ch1), (task2, ch0), (task2,
 *      ch1)] across [Thread0, Thread1].
 *      Number of channels used when defining the (task, channel) pair is fixed to max(`AEC_MAX_Y_CHANNELS`,
 *      `AEC_MAX_X_CHANNELS`).
 */\n\n"""

    fp_tdist_h.write(fp_tdist_h_docstr)

    # Distribute multiple tasks across multiple channels on different cores

    par_tasks_t = """/**
 * @brief Structure used when distributing tasks across hardware threads.
 */ 
typedef struct {
    /** Task index.*/
    int task;
    /** Flag indicating whether the task is active on that core.
     * The task is run on the core only when is_active is set to 1 */
    int is_active;
}par_tasks_t;\n\n"""

    par_tasks_and_channels_t = """/**
 * @brief Structure used when distributing (task, channel) pairs across hardware threads.
 */
typedef struct {
    /** Task index.*/
    int task;
    /** Channel index.*/
    int channel;
    /** Flag indicating whether the (task, channel) pair is active on that core.
     * The (task, channel) pair is run on the core only when is_active is set to 1 */
    int is_active;
}par_tasks_and_channels_t;\n\n"""

    task_distribution_t_str = par_tasks_t  + par_tasks_and_channels_t + "typedef struct {\n"

    fp_c = open(out_dir / c_file_name, 'w')
    fp_c.write(file_header)
    fp_c.write(f'#include "{tdist_h_file_name}"\n\n')
    fp_c.write("/* Structure used for issuing jobs on cores */\n")
    fp_c.write('task_distribution_t tdist = {\n')
    #Schedule 3 tasks, num_channels channels over num_threads threads
    tdist = gen_task_distribution(num_threads, 3, num_channels)
    task_distribution_t_str = print_task_distribution(tdist, 3, num_channels, fp_tdist_h, fp_c, task_distribution_t_str)

    #Schedule 2 tasks, num_channels channels over num_threads threads
    tdist = gen_task_distribution(num_threads, 2, num_channels)
    task_distribution_t_str = print_task_distribution(tdist, 2, num_channels, fp_tdist_h, fp_c, task_distribution_t_str)

    #Schedule 1 tasks, num_channels channels over num_threads threads
    tdist = gen_task_distribution(num_threads, 1, num_channels)
    task_distribution_t_str = print_task_distribution(tdist, 1, num_channels, fp_tdist_h, fp_c,  task_distribution_t_str)

    #Schedule multiple tasks on different cores 
    #Schedule 2 tasks
    tdist = gen_task_distribution(num_threads, 2, 0)
    task_distribution_t_str = print_task_distribution(tdist, 2, 0, fp_tdist_h, fp_c,  task_distribution_t_str)

    #Schedule 3 tasks
    tdist = gen_task_distribution(num_threads, 3, 0)
    task_distribution_t_str = print_task_distribution(tdist, 3, 0, fp_tdist_h, fp_c,  task_distribution_t_str)

    fp_c.write( '};\n')
    fp_c.close()

    task_distribution_t_str += '} task_distribution_t;\n'
    fp_tdist_h.write("\n" + task_distribution_t_str)
    fp_tdist_h.close()

if __name__ == "__main__":
    create_task_distribution()
