#ifndef AGC_INIT_CONFIG_H
#define AGC_INIT_CONFIG_H

#include "agc_conf.h"
#include "agc.h"
/* This is an autogenerated file, please don't modify it manually */

agc_init_config_t agc_init_config __attribute__ ((aligned(8))) = {
    {
        {
            // int adapt -> 1
            1,
            // vtb_uq16_16_t init_gain -> 500
            VTB_UQ16_16(500),
            // vtb_uq16_16_t max_gain -> 1000
            VTB_UQ16_16(1000),
            // vtb_uq1_31_t upper_threshold -> 0.7079
            VTB_UQ1_31(0.7079),
            // vtb_uq1_31_t lower_threshold -> 0.1905
            VTB_UQ1_31(0.1905),
            // vtb_uq16_16_t gain_inc -> 1.197
            VTB_UQ16_16(1.197),
            // vtb_uq16_16_t gain_dec -> 0.87
            VTB_UQ16_16(0.87),
            // int lc_enabled -> 0
            0,
        },
        {
            // int adapt -> 1
            1,
            // vtb_uq16_16_t init_gain -> 500
            VTB_UQ16_16(500),
            // vtb_uq16_16_t max_gain -> 1000
            VTB_UQ16_16(1000),
            // vtb_uq1_31_t upper_threshold -> 0.4
            VTB_UQ1_31(0.4),
            // vtb_uq1_31_t lower_threshold -> 0.4
            VTB_UQ1_31(0.4),
            // vtb_uq16_16_t gain_inc -> 1.0034
            VTB_UQ16_16(1.0034),
            // vtb_uq16_16_t gain_dec -> 0.98804
            VTB_UQ16_16(0.98804),
            // int lc_enabled -> 1
            1,
        },
    }
};

#endif // AGC_INIT_CONFIG_H
