## Source files
file( GLOB_RECURSE    META_DATA_C_SOURCES       src/*.c )

## set META_DATA_INCLUDES & META_DATA_SOURCES
set( META_DATA_INCLUDES     "${CMAKE_CURRENT_LIST_DIR}/api"           )

unset(META_DATA_SOURCES)
list( APPEND  META_DATA_SOURCES   ${META_DATA_C_SOURCES}    )

list( APPEND  META_DATA_SOURCES  ${META_DATA_SOURCES_${CMAKE_SYSTEM_NAME}}        )