set(LIB_NAME lib_vnr)
set(LIB_VERSION 0.9.0)
set(LIB_DEPENDENT_MODULES "lib_xcore_math(2.4.0)")
set(LIB_COMPILER_FLAGS -Os -g -DHEADROOM_CHECK=0)
set(LIB_CXX_SRCS "")

include(${CMAKE_CURRENT_LIST_DIR}/model.cmake)

file(RELATIVE_PATH MODEL_OUT_DIR_REL ${CMAKE_CURRENT_LIST_DIR} ${MODEL_OUT_DIR})

set(LIB_INCLUDES api ${MODEL_OUT_DIR_REL})

file(GLOB VNR_CXX_SOURCES RELATIVE ${CMAKE_CURRENT_LIST_DIR} CONFIGURE_DEPENDS "${CMAKE_CURRENT_LIST_DIR}/src/*.cpp")
file(RELATIVE_PATH VNR_MODEL_SOURCES ${CMAKE_CURRENT_LIST_DIR} ${MODEL_OUT_PATH}.cpp)

list(APPEND LIB_CXX_SRCS ${VNR_MODEL_SOURCES} ${VNR_CXX_SOURCES})

XMOS_REGISTER_MODULE()

# Link aitools with the targets
foreach(target ${APP_BUILD_TARGETS})
    target_link_libraries(${target} PRIVATE tflite_micro)
endforeach()
