// Autogenerated from fwk_voice/modules/lib_vnr/python/utils/xformer/xform_model.py. Do not modify
// Generated using xmos-ai-tools version 0.1.8
#ifndef VNR_TENSOR_ARENA_SIZE_H
#define VNR_TENSOR_ARENA_SIZE_H

#define TENSOR_ARENA_SIZE_BYTES    (19928 - 11304) // Remove model size from the tensor_arena_size returned by the python xcore_tflm_host_interpreter 

#endif