// Autogenerated from fwk_voice/modules/lib_vnr/python/utils/xformer/xform_model.py. Do not modify
// Generated using xmos-ai-tools version 0.1.8
#ifndef VNR_QUANT_SPEC_DEFINES_H
#define VNR_QUANT_SPEC_DEFINES_H

#define VNR_INPUT_SCALE_INV    (1.0/0.1143890991806984)
#define VNR_INPUT_ZERO_POINT   (127)
#define VNR_OUTPUT_SCALE       (0.00390625)
#define VNR_OUTPUT_ZERO_POINT   (-128)

#endif