if(USE_CUSTOM_CMAKE)
    add_subdirectory( test_ns_profile )
    if(${CMAKE_SYSTEM_NAME} STREQUAL XCORE_XS3A)
        add_subdirectory( ns_unit_tests )
    endif()
else()
    cmake_minimum_required(VERSION 3.21)
    include($ENV{XMOS_CMAKE_PATH}/xcommon.cmake)
    project(fwk_voice_tests_ns)
    add_subdirectory(test_ns_xccm)
endif()

