// Autogenerated from /Users/shuchitak/sandboxes/sw_avona_vnr/sw_avona/test/lib_vnr/test_wav_vnr/convert_model.py. Do not modify
// Generated using xmos-ai-tools version 0.1.8.dev99
#ifndef VNR_TENSOR_ARENA_SIZE_H
#define VNR_TENSOR_ARENA_SIZE_H

#define TENSOR_ARENA_SIZE_BYTES    (19944 - 11320) // Remove model size from the tensor_arena_size returned by the python xtflm host interpreter 

#endif