// Autogenerated from /Users/shuchitak/sandboxes/sw_avona_vnr_documentation/sw_avona/test/lib_vnr/test_wav_vnr/convert_model.py. Do not modify
// Generated using xmos-ai-tools version 0.1.8.dev99
#ifndef VNR_QUANT_SPEC_DEFINES_H
#define VNR_QUANT_SPEC_DEFINES_H

#define VNR_INPUT_SCALE_INV    (1.0/0.14669279754161835)
#define VNR_INPUT_ZERO_POINT   (127)
#define VNR_OUTPUT_SCALE       (0.00390625)
#define VNR_OUTPUT_ZERO_POINT   (-128)

#endif