// Copyright 2025 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.

/* Do not edit, autogenerated */

#include "aec_task_distribution.h"

/* Structure used for issuing jobs on cores */
task_distribution_t tdist = {
    {
        {{0, 0, 1},{2, 0, 1},{1, 1, 1},},
        {{1, 0, 1},{0, 1, 1},{2, 1, 1},},
    },
    {
        {{0, 0, 1},{0, 1, 1},},
        {{1, 0, 1},{1, 1, 1},},
    },
    {
        {{0, 0, 1},},
        {{0, 1, 1},},
    },
    {
        {{0, 1},},
        {{1, 1},},
    },
    {
        {{0, 1},{2, 1},},
        {{1, 1},{0, 0},},
    },
};
