TARGET = XCORE-200-EXPLORER

APP_NAME = test_wav_vad

SOURCE_DIRS = src

XCC_FLAGS = -O2 -g -Wall -report

USED_MODULES = lib_vad lib_dsp audio_test_tools

#=============================================================================
# The following part of the Makefile includes the common build infrastructure
# for compiling XMOS applications. You should not need to edit below here.

XMOS_MAKE_PATH ?= ../../..
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
