// Copyright 2025 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.

/* Do not edit, autogenerated */

#pragma once

#define AEC_THREAD_COUNT           (2)
#define AEC_MAX_Y_CHANNELS         (2)
#define AEC_MAX_X_CHANNELS         (2)
#define AEC_MAIN_FILTER_PHASES     (10)
#define AEC_SHADOW_FILTER_PHASES   (5)
