set(LIB_NAME lib_aec)
set(LIB_VERSION 0.9.0)
set(LIB_DEPENDENT_MODULES "lib_xcore_math(2.4.0)")
set(LIB_COMPILER_FLAGS -Os -g)

include(${CMAKE_CURRENT_LIST_DIR}/schedule_xccm.cmake)
set(LIB_INCLUDES api src)

XMOS_REGISTER_MODULE()
if(AUTOGEN_DIR)
    foreach(target ${APP_BUILD_TARGETS})
        target_sources(${target} PRIVATE ${AUTOGEN_SOURCES})
        target_include_directories(${target} PRIVATE ${AUTOGEN_DIR})
        target_compile_definitions(${target} PRIVATE __aec_conf_h_exists__)
    endforeach()
endif()
unset(AUTOGEN_DIR)
