# YAML schema for GitHub Actions:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
#
# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/
#
# This workflow uses actions that are not certified by GitHub. They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support documentation.
#
# This file contains the workflows that are run prior to merging a pull request.

name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

  # Allow manually triggering of the workflow.
  workflow_dispatch: {}

jobs:
  build_apps:
    name: Build UA and INT configurations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Avona
        uses: actions/checkout@v2

      - name: Checkout SDK
        uses: actions/checkout@v2
        with:
          repository: xmos/xcore_sdk
          path: xcore_sdk
          submodules: recursive
          
      - name: Pull xcore_sdk_builder container
        run: |
          docker pull ghcr.io/xmos/sdk_app_builder:develop 
      
      - name: Build
        run: |
          docker run --user $(id -u) --rm -w /sw_avona -e XCORE_SDK_PATH=/sw_avona/xcore_sdk -v ${{ github.workspace }}:/sw_avona ghcr.io/xmos/sdk_app_builder:develop bash -l tools/ci/build_release_configs.sh

      - name: Save firmware artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sw_avona_apps
          path: ./dist
          retention-days: 5

  build_documentation:
    name: Build and package documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Avona
        uses: actions/checkout@v2
      
      - name: Pull doc_builder container
        run: |
          docker pull ghcr.io/xmos/sdk_doc_builder:develop 
      
      - name: Build documentation
        run: |
          docker run --user $(id -u) --rm -w /sw_avona/doc -v ${{ github.workspace }}:/sw_avona ghcr.io/xmos/sdk_doc_builder:develop  make clean html linkcheck SPHINXOPTS="--keep-going"
      
      - name: Save documentation artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sw_avona_docs
          path: ./doc/_build/html
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn` 
          retention-days: 5
